AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla CloudFormation para proyecto DevOps en AWS

Resources:
  DevOpsEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: devops-ec2-cloudformation

  DevOpsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub devops-bucket-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: devops-s3-cloudformation

Outputs:
  InstanceId:
    Description: ID de la instancia EC2 creada
    Value: !Ref DevOpsEC2Instance

  BucketName:
    Description: Nombre del bucket S3 creado
    Value: !Ref DevOpsS3Bucket
