services:
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    networks:
      - devops_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - devops_network
    volumes:
      - ./nginx:/usr/share/nginx/html

networks:
  devops_network:
    driver: bridge
